### ISSUE TITLE
ListFactors API doesn't return certain fields on webauthn factors

### ISSUE THREAD

**Issue by markisherwood** [okta/okta-sdk-dotnet#779]
### Describe the bug?

When I attempt to retrieve the factors for a user, I see duplicates of the `FactorType`, `Profile`, and `Provider` properties in the debugger, one with the expected value and the other with a null value. Attempting to access any of these properties only gives the null value back. I currently only see this issue on `webauthn` factor types. Email and SMS factors also showed this behavior previously but they show as expected since updating to [v9.1.2](https://github.com/okta/okta-sdk-dotnet/releases/tag/v9.1.2). 

The types on the duplicate properties do show as different in the Visual Studio debugger:
Type with `null` -> type with expected value:
* FactorType: `Okta.Sdk.Model.UserFactorType -> string`
* Profile: `Okta.Sdk.Model.UserFactor -> Okta.Sdk.Model.UserFactorWebAuthnProfile`
* Provider: `Okta.Sdk.Model.UserFactor -> Okta.Sdk.Model.UserFactorProvider`

Visual Studio debug output
![Image](https://github.com/user-attachments/assets/9c225a53-25f3-41b8-8d8b-03624de6d556)

Okta API response for same user
```javascript
[
    {
        "id": "sms2bzgxhf5kegrwb0h8",
        "factorType": "sms",
        "provider": "OKTA",
        "vendorName": "OKTA",
        "status": "ACTIVE",
        "created": "2025-02-15T01:50:15.000Z",
        "lastUpdated": "2025-02-15T01:50:15.000Z",
        "profile": {
            "phoneNumber": "...REDACTED..."
        },
        "_links": "...REDACTED..."
    },
    {
        "id": "emf2bw0f9nf1EzGop0h8",
        "factorType": "email",
        "provider": "OKTA",
        "vendorName": "OKTA",
        "status": "ACTIVE",
        "profile": {
            "email": "...REDACTED..."
        },
        "_links": "...REDACTED..."
    },
    {
        "id": "fwf2bw0f30bh40bKu0h8",
        "factorType": "webauthn",
        "provider": "FIDO",
        "vendorName": "FIDO",
        "status": "ACTIVE",
        "created": "2025-02-12T09:33:34.000Z",
        "lastVerified": "2025-02-13T23:37:35.000Z",
        "lastUpdated": "2025-02-12T09:33:34.000Z",
        "profile": {
            "credentialId": "3teAf6wf0qxK74uxtn4waqeklnU7prcvlGSf61JC2V8",
            "appId": null,
            "version": null,
            "authenticatorName": "Windows Hello Hardware Authenticator",
            "presetPinAvailable": null,
            "fulfillmentProvider": null
        },
        "_links": "...REDACTED..."
    }
]
``` 

### What is expected to happen?

I should only see a single instance of these properties with the matching enum like class value.

### What is the actual behavior?

I see two properties with the same name, one with a string value, and one with a null value. Only the null value is returned when I attempt to access the property.

### Reproduction Steps?

1. Enrol user with a passkey
2. Call the `IUserFactorApi.ListFactors(string userId)` API
3. Try to access any of the  `FactorType`, `Profile`, and `Provider` values and receive only the `null` value. Debugger will show the correct underlying string value.

### .NET Version

9.0.102

### SDK Version

v9.1.2

### OS version

BuildNumber
19045

Caption
Microsoft Windows 10 Enterprise  

OSArchitecture
64-bit

Version
10.0.19045

**Comment by aniket-okta** [comment]
Issue is fixed and will be released with v9.3.0.

**Comment by markisherwood** [comment]
Hi @aniket-okta ,

Are you able to confirm the version this is expected to be fixed in? You said v9.3.0 in your comment, but saw a fix mentioned in the [v9.2.1](https://github.com/okta/okta-sdk-dotnet/releases/tag/v9.2.1) release notes.

We've re-tested using v9.2.2 and do see only a single property for `FactorType` which we can access. The issue remains though on the `Profile` and `Provider` fields.

![Image](https://github.com/user-attachments/assets/d276bc47-0778-41f4-8322-39b1a38a073f)

![Image](https://github.com/user-attachments/assets/10bc52c6-6d5a-48ff-869d-f0f171a5dfc7)
